token auth, login and logout
ps-eqsdigital/UNO-OnBoarding pull request #12
Opened 2023-11-02 17:44 UTC by ps-eqsdigital

token authentication
      middleware for jwt authorize
login 
      returns a jwt token
logout
      sets user token to invalid

2023-11-03 10:31 UTC, tentone requested changes

2023-11-03 10:31 UTC, tentone commented on api/Business/BusinessModels/UserBusinessModel.cs
> +
Add docs to models

2023-11-03 10:31 UTC, tentone commented on api/Business/BusinessObjects/UserBusinessObject.cs
> +                }
```suggestion

                if(userToken == null)
                {
                    userToken = new UserTokenAuthentication
                    {
                        UserId = result.Id,
                        Token = token,
                        IsValid = true
                    };
                }
                else
                {
                    userToken.Token = token;
                    userToken.IsValid = true;
                   
                }
                 await _genericDataAccessObject.UpdateAsync<UserTokenAuthentication>(userToken);
```

2023-11-05 19:27 UTC, ps-eqsdigital commented on api/Business/BusinessObjects/UserBusinessObject.cs
> +                }
fixed

2023-11-06 11:02 UTC, js-eqsdigital requested changes

2023-11-06 11:02 UTC, js-eqsdigital commented on api/Business/BusinessObjects/UserBusinessObject.cs
> +                List<User> users =await _userDataAccessObject.FilterUsers(search,sort);
space

2023-11-06 11:02 UTC, js-eqsdigital commented on api/Business/BusinessObjects/UserBusinessObject.cs
> +                if (result.Password != password)
password should be encrypted in db

2023-11-07 20:04 UTC, jocko10 commented on api/Business/BusinessObjects/UserBusinessObject.cs
> +                if (result.Password != password)
fixed

2023-11-07 20:05 UTC, jocko10 commented on api/Business/BusinessObjects/UserBusinessObject.cs
> +                List<User> users =await _userDataAccessObject.FilterUsers(search,sort);
fixed

2023-11-13 10:22 UTC, js-eqsdigital approved these changes

2023-11-13 10:26 UTC, merged